
version: "3.8"

services:
  web:
    image: mcdstate:80
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - type: tmpfs
        target: /tmpfs
      - /home/ubuntu/certs/mcdstate/:/certs
  webssl:
    image: mcdstate:443
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - type: tmpfs
        target: /tmpfs
      - /home/ubuntu/certs/mcdstate/:/certs
